/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.models.shared.GithubConfigureCodeSamplesRequest;
import dev.speakeasyapi.javaclientsdk.utils.Utils;

public class ConfigureCodeSamplesRequestBuilder {

    private GithubConfigureCodeSamplesRequest request;
    private final SDKMethodInterfaces.MethodCallConfigureCodeSamples sdk;

    public ConfigureCodeSamplesRequestBuilder(SDKMethodInterfaces.MethodCallConfigureCodeSamples sdk) {
        this.sdk = sdk;
    }

    public ConfigureCodeSamplesRequestBuilder request(GithubConfigureCodeSamplesRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public ConfigureCodeSamplesResponse call() throws Exception {

        return sdk.configureCodeSamples(
            request);
    }
}
