/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.utils.Utils;

public class GetEmbedAccessTokenRequestBuilder {

    private GetEmbedAccessTokenRequest request;
    private final SDKMethodInterfaces.MethodCallGetEmbedAccessToken sdk;

    public GetEmbedAccessTokenRequestBuilder(SDKMethodInterfaces.MethodCallGetEmbedAccessToken sdk) {
        this.sdk = sdk;
    }

    public GetEmbedAccessTokenRequestBuilder request(GetEmbedAccessTokenRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetEmbedAccessTokenResponse call() throws Exception {

        return sdk.getEmbedAccessToken(
            request);
    }
}
