/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;


public class GetNamespacesRequestBuilder {

    private final SDKMethodInterfaces.MethodCallGetNamespaces sdk;

    public GetNamespacesRequestBuilder(SDKMethodInterfaces.MethodCallGetNamespaces sdk) {
        this.sdk = sdk;
    }

    public GetNamespacesResponse call() throws Exception {

        return sdk.getNamespacesDirect();
    }
}
