/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.speakeasyapi.javaclientsdk.models.shared.WorkspaceFeatureFlagResponse;
import dev.speakeasyapi.javaclientsdk.utils.Response;
import dev.speakeasyapi.javaclientsdk.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;


public class GetWorkspaceFeatureFlagsResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Success
     */
    private Optional<? extends WorkspaceFeatureFlagResponse> workspaceFeatureFlagResponse;

    @JsonCreator
    public GetWorkspaceFeatureFlagsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends WorkspaceFeatureFlagResponse> workspaceFeatureFlagResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(workspaceFeatureFlagResponse, "workspaceFeatureFlagResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.workspaceFeatureFlagResponse = workspaceFeatureFlagResponse;
    }
    
    public GetWorkspaceFeatureFlagsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Success
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<WorkspaceFeatureFlagResponse> workspaceFeatureFlagResponse() {
        return (Optional<WorkspaceFeatureFlagResponse>) workspaceFeatureFlagResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public GetWorkspaceFeatureFlagsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetWorkspaceFeatureFlagsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetWorkspaceFeatureFlagsResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Success
     */
    public GetWorkspaceFeatureFlagsResponse withWorkspaceFeatureFlagResponse(WorkspaceFeatureFlagResponse workspaceFeatureFlagResponse) {
        Utils.checkNotNull(workspaceFeatureFlagResponse, "workspaceFeatureFlagResponse");
        this.workspaceFeatureFlagResponse = Optional.ofNullable(workspaceFeatureFlagResponse);
        return this;
    }

    /**
     * Success
     */
    public GetWorkspaceFeatureFlagsResponse withWorkspaceFeatureFlagResponse(Optional<? extends WorkspaceFeatureFlagResponse> workspaceFeatureFlagResponse) {
        Utils.checkNotNull(workspaceFeatureFlagResponse, "workspaceFeatureFlagResponse");
        this.workspaceFeatureFlagResponse = workspaceFeatureFlagResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetWorkspaceFeatureFlagsResponse other = (GetWorkspaceFeatureFlagsResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.workspaceFeatureFlagResponse, other.workspaceFeatureFlagResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            workspaceFeatureFlagResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetWorkspaceFeatureFlagsResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "workspaceFeatureFlagResponse", workspaceFeatureFlagResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends WorkspaceFeatureFlagResponse> workspaceFeatureFlagResponse = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Success
         */
        public Builder workspaceFeatureFlagResponse(WorkspaceFeatureFlagResponse workspaceFeatureFlagResponse) {
            Utils.checkNotNull(workspaceFeatureFlagResponse, "workspaceFeatureFlagResponse");
            this.workspaceFeatureFlagResponse = Optional.ofNullable(workspaceFeatureFlagResponse);
            return this;
        }

        /**
         * Success
         */
        public Builder workspaceFeatureFlagResponse(Optional<? extends WorkspaceFeatureFlagResponse> workspaceFeatureFlagResponse) {
            Utils.checkNotNull(workspaceFeatureFlagResponse, "workspaceFeatureFlagResponse");
            this.workspaceFeatureFlagResponse = workspaceFeatureFlagResponse;
            return this;
        }
        
        public GetWorkspaceFeatureFlagsResponse build() {
            return new GetWorkspaceFeatureFlagsResponse(
                contentType,
                statusCode,
                rawResponse,
                workspaceFeatureFlagResponse);
        }
    }
}

