/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk;

import dev.speakeasyapi.javaclientsdk.utils.HTTPClient;
import dev.speakeasyapi.javaclientsdk.models.shared.Security;

class SDKConfiguration {
	public SecuritySource securitySource;	
    
	public HTTPClient defaultClient;
	public String serverUrl;
	public String server;
	public String language = "java";
	public String openapiDocVersion = "0.3.0";
	public String sdkVersion = "6.0.0";
	public String genVersion = "2.248.6";
	public String userAgent = "speakeasy-sdk/java 6.0.0 2.248.6 0.3.0 dev.speakeasyapi.javaclientsdk";
	
	
}