/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;
import java.io.InputStream;

/**
 * InteractionType - Type of interaction.
 */
public enum InteractionType {
    CLI_EXEC("CLI_EXEC"),
    TARGET_GENERATE("TARGET_GENERATE");

    @JsonValue
    private final String value;

    private InteractionType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
