/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.shared;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.speakeasyapi.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.Optional;

/**
 * EmbedToken - A representation of an embed token granted for working with Speakeasy components.
 */

public class EmbedToken {

    /**
     * Creation timestamp.
     */
    @JsonProperty("created_at")
    private OffsetDateTime createdAt;

    /**
     * The ID of the user that created this token.
     */
    @JsonProperty("created_by")
    private String createdBy;

    /**
     * A detailed description of the EmbedToken.
     */
    @JsonProperty("description")
    private String description;

    /**
     * The time this token expires.
     */
    @JsonProperty("expires_at")
    private OffsetDateTime expiresAt;

    /**
     * The filters applied to this token.
     */
    @JsonProperty("filters")
    private String filters;

    /**
     * The ID of this EmbedToken.
     */
    @JsonProperty("id")
    private String id;

    /**
     * The last time this token was used.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("last_used")
    private Optional<OffsetDateTime> lastUsed;

    /**
     * The time this token was revoked.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("revoked_at")
    private Optional<OffsetDateTime> revokedAt;

    /**
     * The ID of the user that revoked this token.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("revoked_by")
    private Optional<String> revokedBy;

    /**
     * The workspace ID this token belongs to.
     */
    @JsonProperty("workspace_id")
    private String workspaceId;

    @JsonCreator
    public EmbedToken(
            @JsonProperty("created_at") OffsetDateTime createdAt,
            @JsonProperty("created_by") String createdBy,
            @JsonProperty("description") String description,
            @JsonProperty("expires_at") OffsetDateTime expiresAt,
            @JsonProperty("filters") String filters,
            @JsonProperty("id") String id,
            @JsonProperty("last_used") Optional<OffsetDateTime> lastUsed,
            @JsonProperty("revoked_at") Optional<OffsetDateTime> revokedAt,
            @JsonProperty("revoked_by") Optional<String> revokedBy,
            @JsonProperty("workspace_id") String workspaceId) {
        Utils.checkNotNull(createdAt, "createdAt");
        Utils.checkNotNull(createdBy, "createdBy");
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(expiresAt, "expiresAt");
        Utils.checkNotNull(filters, "filters");
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(lastUsed, "lastUsed");
        Utils.checkNotNull(revokedAt, "revokedAt");
        Utils.checkNotNull(revokedBy, "revokedBy");
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.description = description;
        this.expiresAt = expiresAt;
        this.filters = filters;
        this.id = id;
        this.lastUsed = lastUsed;
        this.revokedAt = revokedAt;
        this.revokedBy = revokedBy;
        this.workspaceId = workspaceId;
    }
    
    public EmbedToken(
            OffsetDateTime createdAt,
            String createdBy,
            String description,
            OffsetDateTime expiresAt,
            String filters,
            String id,
            String workspaceId) {
        this(createdAt, createdBy, description, expiresAt, filters, id, Optional.empty(), Optional.empty(), Optional.empty(), workspaceId);
    }

    /**
     * Creation timestamp.
     */
    @JsonIgnore
    public OffsetDateTime createdAt() {
        return createdAt;
    }

    /**
     * The ID of the user that created this token.
     */
    @JsonIgnore
    public String createdBy() {
        return createdBy;
    }

    /**
     * A detailed description of the EmbedToken.
     */
    @JsonIgnore
    public String description() {
        return description;
    }

    /**
     * The time this token expires.
     */
    @JsonIgnore
    public OffsetDateTime expiresAt() {
        return expiresAt;
    }

    /**
     * The filters applied to this token.
     */
    @JsonIgnore
    public String filters() {
        return filters;
    }

    /**
     * The ID of this EmbedToken.
     */
    @JsonIgnore
    public String id() {
        return id;
    }

    /**
     * The last time this token was used.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> lastUsed() {
        return lastUsed;
    }

    /**
     * The time this token was revoked.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> revokedAt() {
        return revokedAt;
    }

    /**
     * The ID of the user that revoked this token.
     */
    @JsonIgnore
    public Optional<String> revokedBy() {
        return revokedBy;
    }

    /**
     * The workspace ID this token belongs to.
     */
    @JsonIgnore
    public String workspaceId() {
        return workspaceId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Creation timestamp.
     */
    public EmbedToken withCreatedAt(OffsetDateTime createdAt) {
        Utils.checkNotNull(createdAt, "createdAt");
        this.createdAt = createdAt;
        return this;
    }

    /**
     * The ID of the user that created this token.
     */
    public EmbedToken withCreatedBy(String createdBy) {
        Utils.checkNotNull(createdBy, "createdBy");
        this.createdBy = createdBy;
        return this;
    }

    /**
     * A detailed description of the EmbedToken.
     */
    public EmbedToken withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    /**
     * The time this token expires.
     */
    public EmbedToken withExpiresAt(OffsetDateTime expiresAt) {
        Utils.checkNotNull(expiresAt, "expiresAt");
        this.expiresAt = expiresAt;
        return this;
    }

    /**
     * The filters applied to this token.
     */
    public EmbedToken withFilters(String filters) {
        Utils.checkNotNull(filters, "filters");
        this.filters = filters;
        return this;
    }

    /**
     * The ID of this EmbedToken.
     */
    public EmbedToken withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * The last time this token was used.
     */
    public EmbedToken withLastUsed(OffsetDateTime lastUsed) {
        Utils.checkNotNull(lastUsed, "lastUsed");
        this.lastUsed = Optional.ofNullable(lastUsed);
        return this;
    }

    /**
     * The last time this token was used.
     */
    public EmbedToken withLastUsed(Optional<OffsetDateTime> lastUsed) {
        Utils.checkNotNull(lastUsed, "lastUsed");
        this.lastUsed = lastUsed;
        return this;
    }

    /**
     * The time this token was revoked.
     */
    public EmbedToken withRevokedAt(OffsetDateTime revokedAt) {
        Utils.checkNotNull(revokedAt, "revokedAt");
        this.revokedAt = Optional.ofNullable(revokedAt);
        return this;
    }

    /**
     * The time this token was revoked.
     */
    public EmbedToken withRevokedAt(Optional<OffsetDateTime> revokedAt) {
        Utils.checkNotNull(revokedAt, "revokedAt");
        this.revokedAt = revokedAt;
        return this;
    }

    /**
     * The ID of the user that revoked this token.
     */
    public EmbedToken withRevokedBy(String revokedBy) {
        Utils.checkNotNull(revokedBy, "revokedBy");
        this.revokedBy = Optional.ofNullable(revokedBy);
        return this;
    }

    /**
     * The ID of the user that revoked this token.
     */
    public EmbedToken withRevokedBy(Optional<String> revokedBy) {
        Utils.checkNotNull(revokedBy, "revokedBy");
        this.revokedBy = revokedBy;
        return this;
    }

    /**
     * The workspace ID this token belongs to.
     */
    public EmbedToken withWorkspaceId(String workspaceId) {
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.workspaceId = workspaceId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EmbedToken other = (EmbedToken) o;
        return 
            Objects.deepEquals(this.createdAt, other.createdAt) &&
            Objects.deepEquals(this.createdBy, other.createdBy) &&
            Objects.deepEquals(this.description, other.description) &&
            Objects.deepEquals(this.expiresAt, other.expiresAt) &&
            Objects.deepEquals(this.filters, other.filters) &&
            Objects.deepEquals(this.id, other.id) &&
            Objects.deepEquals(this.lastUsed, other.lastUsed) &&
            Objects.deepEquals(this.revokedAt, other.revokedAt) &&
            Objects.deepEquals(this.revokedBy, other.revokedBy) &&
            Objects.deepEquals(this.workspaceId, other.workspaceId);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            createdAt,
            createdBy,
            description,
            expiresAt,
            filters,
            id,
            lastUsed,
            revokedAt,
            revokedBy,
            workspaceId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(EmbedToken.class,
                "createdAt", createdAt,
                "createdBy", createdBy,
                "description", description,
                "expiresAt", expiresAt,
                "filters", filters,
                "id", id,
                "lastUsed", lastUsed,
                "revokedAt", revokedAt,
                "revokedBy", revokedBy,
                "workspaceId", workspaceId);
    }
    
    public final static class Builder {
 
        private OffsetDateTime createdAt;
 
        private String createdBy;
 
        private String description;
 
        private OffsetDateTime expiresAt;
 
        private String filters;
 
        private String id;
 
        private Optional<OffsetDateTime> lastUsed = Optional.empty();
 
        private Optional<OffsetDateTime> revokedAt = Optional.empty();
 
        private Optional<String> revokedBy = Optional.empty();
 
        private String workspaceId;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Creation timestamp.
         */
        public Builder createdAt(OffsetDateTime createdAt) {
            Utils.checkNotNull(createdAt, "createdAt");
            this.createdAt = createdAt;
            return this;
        }

        /**
         * The ID of the user that created this token.
         */
        public Builder createdBy(String createdBy) {
            Utils.checkNotNull(createdBy, "createdBy");
            this.createdBy = createdBy;
            return this;
        }

        /**
         * A detailed description of the EmbedToken.
         */
        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }

        /**
         * The time this token expires.
         */
        public Builder expiresAt(OffsetDateTime expiresAt) {
            Utils.checkNotNull(expiresAt, "expiresAt");
            this.expiresAt = expiresAt;
            return this;
        }

        /**
         * The filters applied to this token.
         */
        public Builder filters(String filters) {
            Utils.checkNotNull(filters, "filters");
            this.filters = filters;
            return this;
        }

        /**
         * The ID of this EmbedToken.
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        /**
         * The last time this token was used.
         */
        public Builder lastUsed(OffsetDateTime lastUsed) {
            Utils.checkNotNull(lastUsed, "lastUsed");
            this.lastUsed = Optional.ofNullable(lastUsed);
            return this;
        }

        /**
         * The last time this token was used.
         */
        public Builder lastUsed(Optional<OffsetDateTime> lastUsed) {
            Utils.checkNotNull(lastUsed, "lastUsed");
            this.lastUsed = lastUsed;
            return this;
        }

        /**
         * The time this token was revoked.
         */
        public Builder revokedAt(OffsetDateTime revokedAt) {
            Utils.checkNotNull(revokedAt, "revokedAt");
            this.revokedAt = Optional.ofNullable(revokedAt);
            return this;
        }

        /**
         * The time this token was revoked.
         */
        public Builder revokedAt(Optional<OffsetDateTime> revokedAt) {
            Utils.checkNotNull(revokedAt, "revokedAt");
            this.revokedAt = revokedAt;
            return this;
        }

        /**
         * The ID of the user that revoked this token.
         */
        public Builder revokedBy(String revokedBy) {
            Utils.checkNotNull(revokedBy, "revokedBy");
            this.revokedBy = Optional.ofNullable(revokedBy);
            return this;
        }

        /**
         * The ID of the user that revoked this token.
         */
        public Builder revokedBy(Optional<String> revokedBy) {
            Utils.checkNotNull(revokedBy, "revokedBy");
            this.revokedBy = revokedBy;
            return this;
        }

        /**
         * The workspace ID this token belongs to.
         */
        public Builder workspaceId(String workspaceId) {
            Utils.checkNotNull(workspaceId, "workspaceId");
            this.workspaceId = workspaceId;
            return this;
        }
        
        public EmbedToken build() {
            return new EmbedToken(
                createdAt,
                createdBy,
                description,
                expiresAt,
                filters,
                id,
                lastUsed,
                revokedAt,
                revokedBy,
                workspaceId);
        }
    }
}

