/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.shared;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.speakeasyapi.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;


public class OASOperation {

    @JsonProperty("description")
    private String description;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("group_override")
    private Optional<String> groupOverride;

    @JsonProperty("method")
    private String method;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("method_name_override")
    private Optional<String> methodNameOverride;

    @JsonProperty("operation_id")
    private String operationId;

    @JsonProperty("path")
    private String path;

    @JsonProperty("tags")
    private List<String> tags;

    @JsonCreator
    public OASOperation(
            @JsonProperty("description") String description,
            @JsonProperty("group_override") Optional<String> groupOverride,
            @JsonProperty("method") String method,
            @JsonProperty("method_name_override") Optional<String> methodNameOverride,
            @JsonProperty("operation_id") String operationId,
            @JsonProperty("path") String path,
            @JsonProperty("tags") List<String> tags) {
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(groupOverride, "groupOverride");
        Utils.checkNotNull(method, "method");
        Utils.checkNotNull(methodNameOverride, "methodNameOverride");
        Utils.checkNotNull(operationId, "operationId");
        Utils.checkNotNull(path, "path");
        Utils.checkNotNull(tags, "tags");
        this.description = description;
        this.groupOverride = groupOverride;
        this.method = method;
        this.methodNameOverride = methodNameOverride;
        this.operationId = operationId;
        this.path = path;
        this.tags = tags;
    }
    
    public OASOperation(
            String description,
            String method,
            String operationId,
            String path,
            List<String> tags) {
        this(description, Optional.empty(), method, Optional.empty(), operationId, path, tags);
    }

    @JsonIgnore
    public String description() {
        return description;
    }

    @JsonIgnore
    public Optional<String> groupOverride() {
        return groupOverride;
    }

    @JsonIgnore
    public String method() {
        return method;
    }

    @JsonIgnore
    public Optional<String> methodNameOverride() {
        return methodNameOverride;
    }

    @JsonIgnore
    public String operationId() {
        return operationId;
    }

    @JsonIgnore
    public String path() {
        return path;
    }

    @JsonIgnore
    public List<String> tags() {
        return tags;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public OASOperation withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    public OASOperation withGroupOverride(String groupOverride) {
        Utils.checkNotNull(groupOverride, "groupOverride");
        this.groupOverride = Optional.ofNullable(groupOverride);
        return this;
    }

    public OASOperation withGroupOverride(Optional<String> groupOverride) {
        Utils.checkNotNull(groupOverride, "groupOverride");
        this.groupOverride = groupOverride;
        return this;
    }

    public OASOperation withMethod(String method) {
        Utils.checkNotNull(method, "method");
        this.method = method;
        return this;
    }

    public OASOperation withMethodNameOverride(String methodNameOverride) {
        Utils.checkNotNull(methodNameOverride, "methodNameOverride");
        this.methodNameOverride = Optional.ofNullable(methodNameOverride);
        return this;
    }

    public OASOperation withMethodNameOverride(Optional<String> methodNameOverride) {
        Utils.checkNotNull(methodNameOverride, "methodNameOverride");
        this.methodNameOverride = methodNameOverride;
        return this;
    }

    public OASOperation withOperationId(String operationId) {
        Utils.checkNotNull(operationId, "operationId");
        this.operationId = operationId;
        return this;
    }

    public OASOperation withPath(String path) {
        Utils.checkNotNull(path, "path");
        this.path = path;
        return this;
    }

    public OASOperation withTags(List<String> tags) {
        Utils.checkNotNull(tags, "tags");
        this.tags = tags;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OASOperation other = (OASOperation) o;
        return 
            Objects.deepEquals(this.description, other.description) &&
            Objects.deepEquals(this.groupOverride, other.groupOverride) &&
            Objects.deepEquals(this.method, other.method) &&
            Objects.deepEquals(this.methodNameOverride, other.methodNameOverride) &&
            Objects.deepEquals(this.operationId, other.operationId) &&
            Objects.deepEquals(this.path, other.path) &&
            Objects.deepEquals(this.tags, other.tags);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            description,
            groupOverride,
            method,
            methodNameOverride,
            operationId,
            path,
            tags);
    }
    
    @Override
    public String toString() {
        return Utils.toString(OASOperation.class,
                "description", description,
                "groupOverride", groupOverride,
                "method", method,
                "methodNameOverride", methodNameOverride,
                "operationId", operationId,
                "path", path,
                "tags", tags);
    }
    
    public final static class Builder {
 
        private String description;
 
        private Optional<String> groupOverride = Optional.empty();
 
        private String method;
 
        private Optional<String> methodNameOverride = Optional.empty();
 
        private String operationId;
 
        private String path;
 
        private List<String> tags;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }

        public Builder groupOverride(String groupOverride) {
            Utils.checkNotNull(groupOverride, "groupOverride");
            this.groupOverride = Optional.ofNullable(groupOverride);
            return this;
        }

        public Builder groupOverride(Optional<String> groupOverride) {
            Utils.checkNotNull(groupOverride, "groupOverride");
            this.groupOverride = groupOverride;
            return this;
        }

        public Builder method(String method) {
            Utils.checkNotNull(method, "method");
            this.method = method;
            return this;
        }

        public Builder methodNameOverride(String methodNameOverride) {
            Utils.checkNotNull(methodNameOverride, "methodNameOverride");
            this.methodNameOverride = Optional.ofNullable(methodNameOverride);
            return this;
        }

        public Builder methodNameOverride(Optional<String> methodNameOverride) {
            Utils.checkNotNull(methodNameOverride, "methodNameOverride");
            this.methodNameOverride = methodNameOverride;
            return this;
        }

        public Builder operationId(String operationId) {
            Utils.checkNotNull(operationId, "operationId");
            this.operationId = operationId;
            return this;
        }

        public Builder path(String path) {
            Utils.checkNotNull(path, "path");
            this.path = path;
            return this;
        }

        public Builder tags(List<String> tags) {
            Utils.checkNotNull(tags, "tags");
            this.tags = tags;
            return this;
        }
        
        public OASOperation build() {
            return new OASOperation(
                description,
                groupOverride,
                method,
                methodNameOverride,
                operationId,
                path,
                tags);
        }
    }
}

