/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.speakeasy_sdks_staging.javaclientsdk.utils.SpeakeasyMetadata;


public class InsertVersionMetadataRequest {
    /**
     * A JSON representation of the metadata to insert.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public io.github.speakeasy_sdks_staging.javaclientsdk.models.shared.VersionMetadataInput versionMetadata;

    public InsertVersionMetadataRequest withVersionMetadata(io.github.speakeasy_sdks_staging.javaclientsdk.models.shared.VersionMetadataInput versionMetadata) {
        this.versionMetadata = versionMetadata;
        return this;
    }
    
    /**
     * The ID of the Api to insert metadata for.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=apiID")
    public String apiID;

    public InsertVersionMetadataRequest withApiID(String apiID) {
        this.apiID = apiID;
        return this;
    }
    
    /**
     * The version ID of the Api to insert metadata for.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=versionID")
    public String versionID;

    public InsertVersionMetadataRequest withVersionID(String versionID) {
        this.versionID = versionID;
        return this;
    }
    
    public InsertVersionMetadataRequest(@JsonProperty("VersionMetadata") io.github.speakeasy_sdks_staging.javaclientsdk.models.shared.VersionMetadataInput versionMetadata, @JsonProperty("apiID") String apiID, @JsonProperty("versionID") String versionID) {
        this.versionMetadata = versionMetadata;
        this.apiID = apiID;
        this.versionID = versionID;
  }
}
