/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import dev.speakeasyapi.javaclientsdk.utils.Utils;
import java.io.InputStream;
import java.net.http.HttpResponse;
import java.util.Optional;


public class DownloadSchemaRevisionResponse {

    /**
     * OK
     */
    private Optional<? extends InputStream> twoHundredApplicationJsonSchema;

    /**
     * OK
     */
    private Optional<? extends InputStream> twoHundredApplicationXYamlSchema;

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * Default error response
     */
    private Optional<? extends dev.speakeasyapi.javaclientsdk.models.shared.Error> error;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    public DownloadSchemaRevisionResponse(
            Optional<? extends InputStream> twoHundredApplicationJsonSchema,
            Optional<? extends InputStream> twoHundredApplicationXYamlSchema,
            String contentType,
            Optional<? extends dev.speakeasyapi.javaclientsdk.models.shared.Error> error,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(twoHundredApplicationJsonSchema, "twoHundredApplicationJsonSchema");
        Utils.checkNotNull(twoHundredApplicationXYamlSchema, "twoHundredApplicationXYamlSchema");
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(error, "error");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.twoHundredApplicationJsonSchema = twoHundredApplicationJsonSchema;
        this.twoHundredApplicationXYamlSchema = twoHundredApplicationXYamlSchema;
        this.contentType = contentType;
        this.error = error;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }

    /**
     * OK
     */
    public Optional<? extends InputStream> twoHundredApplicationJsonSchema() {
        return twoHundredApplicationJsonSchema;
    }

    /**
     * OK
     */
    public Optional<? extends InputStream> twoHundredApplicationXYamlSchema() {
        return twoHundredApplicationXYamlSchema;
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return contentType;
    }

    /**
     * Default error response
     */
    public Optional<? extends dev.speakeasyapi.javaclientsdk.models.shared.Error> error() {
        return error;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }
    
    public final static Builder builder() {
        return new Builder();
    }

    /**
     * OK
     */
    public DownloadSchemaRevisionResponse withTwoHundredApplicationJsonSchema(InputStream twoHundredApplicationJsonSchema) {
        Utils.checkNotNull(twoHundredApplicationJsonSchema, "twoHundredApplicationJsonSchema");
        this.twoHundredApplicationJsonSchema = Optional.ofNullable(twoHundredApplicationJsonSchema);
        return this;
    }
    
    /**
     * OK
     */
    public DownloadSchemaRevisionResponse withTwoHundredApplicationJsonSchema(Optional<? extends InputStream> twoHundredApplicationJsonSchema) {
        Utils.checkNotNull(twoHundredApplicationJsonSchema, "twoHundredApplicationJsonSchema");
        this.twoHundredApplicationJsonSchema = twoHundredApplicationJsonSchema;
        return this;
    }

    /**
     * OK
     */
    public DownloadSchemaRevisionResponse withTwoHundredApplicationXYamlSchema(InputStream twoHundredApplicationXYamlSchema) {
        Utils.checkNotNull(twoHundredApplicationXYamlSchema, "twoHundredApplicationXYamlSchema");
        this.twoHundredApplicationXYamlSchema = Optional.ofNullable(twoHundredApplicationXYamlSchema);
        return this;
    }
    
    /**
     * OK
     */
    public DownloadSchemaRevisionResponse withTwoHundredApplicationXYamlSchema(Optional<? extends InputStream> twoHundredApplicationXYamlSchema) {
        Utils.checkNotNull(twoHundredApplicationXYamlSchema, "twoHundredApplicationXYamlSchema");
        this.twoHundredApplicationXYamlSchema = twoHundredApplicationXYamlSchema;
        return this;
    }

    /**
     * HTTP response content type for this operation
     */
    public DownloadSchemaRevisionResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * Default error response
     */
    public DownloadSchemaRevisionResponse withError(dev.speakeasyapi.javaclientsdk.models.shared.Error error) {
        Utils.checkNotNull(error, "error");
        this.error = Optional.ofNullable(error);
        return this;
    }
    
    /**
     * Default error response
     */
    public DownloadSchemaRevisionResponse withError(Optional<? extends dev.speakeasyapi.javaclientsdk.models.shared.Error> error) {
        Utils.checkNotNull(error, "error");
        this.error = error;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public DownloadSchemaRevisionResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public DownloadSchemaRevisionResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DownloadSchemaRevisionResponse other = (DownloadSchemaRevisionResponse) o;
        return 
            java.util.Objects.deepEquals(this.twoHundredApplicationJsonSchema, other.twoHundredApplicationJsonSchema) &&
            java.util.Objects.deepEquals(this.twoHundredApplicationXYamlSchema, other.twoHundredApplicationXYamlSchema) &&
            java.util.Objects.deepEquals(this.contentType, other.contentType) &&
            java.util.Objects.deepEquals(this.error, other.error) &&
            java.util.Objects.deepEquals(this.statusCode, other.statusCode) &&
            java.util.Objects.deepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            twoHundredApplicationJsonSchema,
            twoHundredApplicationXYamlSchema,
            contentType,
            error,
            statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DownloadSchemaRevisionResponse.class,
                "twoHundredApplicationJsonSchema", twoHundredApplicationJsonSchema,
                "twoHundredApplicationXYamlSchema", twoHundredApplicationXYamlSchema,
                "contentType", contentType,
                "error", error,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }
    
    public final static class Builder {
 
        private Optional<? extends InputStream> twoHundredApplicationJsonSchema = Optional.empty();
 
        private Optional<? extends InputStream> twoHundredApplicationXYamlSchema = Optional.empty();
 
        private String contentType;
 
        private Optional<? extends dev.speakeasyapi.javaclientsdk.models.shared.Error> error = Optional.empty();
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * OK
         */
        public Builder twoHundredApplicationJsonSchema(InputStream twoHundredApplicationJsonSchema) {
            Utils.checkNotNull(twoHundredApplicationJsonSchema, "twoHundredApplicationJsonSchema");
            this.twoHundredApplicationJsonSchema = Optional.ofNullable(twoHundredApplicationJsonSchema);
            return this;
        }
        
        /**
         * OK
         */
        public Builder twoHundredApplicationJsonSchema(Optional<? extends InputStream> twoHundredApplicationJsonSchema) {
            Utils.checkNotNull(twoHundredApplicationJsonSchema, "twoHundredApplicationJsonSchema");
            this.twoHundredApplicationJsonSchema = twoHundredApplicationJsonSchema;
            return this;
        }

        /**
         * OK
         */
        public Builder twoHundredApplicationXYamlSchema(InputStream twoHundredApplicationXYamlSchema) {
            Utils.checkNotNull(twoHundredApplicationXYamlSchema, "twoHundredApplicationXYamlSchema");
            this.twoHundredApplicationXYamlSchema = Optional.ofNullable(twoHundredApplicationXYamlSchema);
            return this;
        }
        
        /**
         * OK
         */
        public Builder twoHundredApplicationXYamlSchema(Optional<? extends InputStream> twoHundredApplicationXYamlSchema) {
            Utils.checkNotNull(twoHundredApplicationXYamlSchema, "twoHundredApplicationXYamlSchema");
            this.twoHundredApplicationXYamlSchema = twoHundredApplicationXYamlSchema;
            return this;
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * Default error response
         */
        public Builder error(dev.speakeasyapi.javaclientsdk.models.shared.Error error) {
            Utils.checkNotNull(error, "error");
            this.error = Optional.ofNullable(error);
            return this;
        }
        
        /**
         * Default error response
         */
        public Builder error(Optional<? extends dev.speakeasyapi.javaclientsdk.models.shared.Error> error) {
            Utils.checkNotNull(error, "error");
            this.error = error;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }        
        
        public DownloadSchemaRevisionResponse build() {
            return new DownloadSchemaRevisionResponse(
                twoHundredApplicationJsonSchema,
                twoHundredApplicationXYamlSchema,
                contentType,
                error,
                statusCode,
                rawResponse);
        }
    }
}

