/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;



public class GenerateRequestPostmanCollectionRequest {
    public GenerateRequestPostmanCollectionPathParams pathParams;
    public GenerateRequestPostmanCollectionRequest withPathParams(GenerateRequestPostmanCollectionPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
