/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

import dev.speakeasyapi.javaclientsdk.SDK;
import dev.speakeasyapi.javaclientsdk.utils.Utils;
import dev.speakeasyapi.javaclientsdk.utils.LazySingletonValue;

public class GetApiEndpointRequestBuilder {

    private GetApiEndpointRequest request;

    private final SDKMethodInterfaces.MethodCallGetApiEndpoint sdk;
    
    public GetApiEndpointRequestBuilder(SDKMethodInterfaces.MethodCallGetApiEndpoint sdk) {
        this.sdk = sdk;
    }
             
    public GetApiEndpointRequestBuilder request(GetApiEndpointRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetApiEndpointResponse call() throws Exception {
        return sdk.getApiEndpoint(
            request);
    }
}