/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package dev.speakeasyapi.javaclientsdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import dev.speakeasyapi.javaclientsdk.utils.SpeakeasyMetadata;


public class UpsertApiRequest {
    /**
     * A JSON representation of the Api to upsert
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public dev.speakeasyapi.javaclientsdk.models.shared.ApiInput api;

    public UpsertApiRequest withApi(dev.speakeasyapi.javaclientsdk.models.shared.ApiInput api) {
        this.api = api;
        return this;
    }
    
    /**
     * The ID of the Api to upsert.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=apiID")
    public String apiID;

    public UpsertApiRequest withApiID(String apiID) {
        this.apiID = apiID;
        return this;
    }
    
    public UpsertApiRequest(@JsonProperty("Api") dev.speakeasyapi.javaclientsdk.models.shared.ApiInput api, @JsonProperty("apiID") String apiID) {
        this.api = api;
        this.apiID = apiID;
  }
}
