/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

public class GetRevisionsResponse {

    @JsonProperty("items")
    private java.util.List<Revision> items;

    @JsonProperty("next_page_token")
    private String nextPageToken;

    @JsonCreator
    public GetRevisionsResponse(
            @JsonProperty("items") java.util.List<Revision> items,
            @JsonProperty("next_page_token") String nextPageToken) {
        Utils.checkNotNull(items, "items");
        Utils.checkNotNull(nextPageToken, "nextPageToken");
        this.items = items;
        this.nextPageToken = nextPageToken;
    }

    @JsonIgnore
    public java.util.List<Revision> items() {
        return items;
    }

    @JsonIgnore
    public String nextPageToken() {
        return nextPageToken;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public GetRevisionsResponse withItems(java.util.List<Revision> items) {
        Utils.checkNotNull(items, "items");
        this.items = items;
        return this;
    }

    public GetRevisionsResponse withNextPageToken(String nextPageToken) {
        Utils.checkNotNull(nextPageToken, "nextPageToken");
        this.nextPageToken = nextPageToken;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetRevisionsResponse other = (GetRevisionsResponse) o;
        return 
            java.util.Objects.deepEquals(this.items, other.items) &&
            java.util.Objects.deepEquals(this.nextPageToken, other.nextPageToken);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            items,
            nextPageToken);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetRevisionsResponse.class,
                "items", items,
                "nextPageToken", nextPageToken);
    }
    
    public final static class Builder {
 
        private java.util.List<Revision> items;
 
        private String nextPageToken;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder items(java.util.List<Revision> items) {
            Utils.checkNotNull(items, "items");
            this.items = items;
            return this;
        }

        public Builder nextPageToken(String nextPageToken) {
            Utils.checkNotNull(nextPageToken, "nextPageToken");
            this.nextPageToken = nextPageToken;
            return this;
        }
        
        public GetRevisionsResponse build() {
            return new GetRevisionsResponse(
                items,
                nextPageToken);
        }
    }
}

