/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.shared;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * GithubTriggerActionRequest - A request to trigger an action on a GitHub target
 */

public class GithubTriggerActionRequest {

    /**
     * The generation lock ID
     */
    @JsonProperty("gen_lock_id")
    private String genLockId;

    /**
     * The GitHub organization name
     */
    @JsonProperty("org")
    private String org;

    /**
     * The GitHub repository name
     */
    @JsonProperty("repo_name")
    private String repoName;

    /**
     * A version to override the SDK too in workflow dispatch
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("set_version")
    private Optional<String> setVersion;

    /**
     * The target name for the action
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("target_name")
    private Optional<String> targetName;

    @JsonCreator
    public GithubTriggerActionRequest(
            @JsonProperty("gen_lock_id") String genLockId,
            @JsonProperty("org") String org,
            @JsonProperty("repo_name") String repoName,
            @JsonProperty("set_version") Optional<String> setVersion,
            @JsonProperty("target_name") Optional<String> targetName) {
        Utils.checkNotNull(genLockId, "genLockId");
        Utils.checkNotNull(org, "org");
        Utils.checkNotNull(repoName, "repoName");
        Utils.checkNotNull(setVersion, "setVersion");
        Utils.checkNotNull(targetName, "targetName");
        this.genLockId = genLockId;
        this.org = org;
        this.repoName = repoName;
        this.setVersion = setVersion;
        this.targetName = targetName;
    }
    
    public GithubTriggerActionRequest(
            String genLockId,
            String org,
            String repoName) {
        this(genLockId, org, repoName, Optional.empty(), Optional.empty());
    }

    /**
     * The generation lock ID
     */
    @JsonIgnore
    public String genLockId() {
        return genLockId;
    }

    /**
     * The GitHub organization name
     */
    @JsonIgnore
    public String org() {
        return org;
    }

    /**
     * The GitHub repository name
     */
    @JsonIgnore
    public String repoName() {
        return repoName;
    }

    /**
     * A version to override the SDK too in workflow dispatch
     */
    @JsonIgnore
    public Optional<String> setVersion() {
        return setVersion;
    }

    /**
     * The target name for the action
     */
    @JsonIgnore
    public Optional<String> targetName() {
        return targetName;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The generation lock ID
     */
    public GithubTriggerActionRequest withGenLockId(String genLockId) {
        Utils.checkNotNull(genLockId, "genLockId");
        this.genLockId = genLockId;
        return this;
    }

    /**
     * The GitHub organization name
     */
    public GithubTriggerActionRequest withOrg(String org) {
        Utils.checkNotNull(org, "org");
        this.org = org;
        return this;
    }

    /**
     * The GitHub repository name
     */
    public GithubTriggerActionRequest withRepoName(String repoName) {
        Utils.checkNotNull(repoName, "repoName");
        this.repoName = repoName;
        return this;
    }

    /**
     * A version to override the SDK too in workflow dispatch
     */
    public GithubTriggerActionRequest withSetVersion(String setVersion) {
        Utils.checkNotNull(setVersion, "setVersion");
        this.setVersion = Optional.ofNullable(setVersion);
        return this;
    }

    /**
     * A version to override the SDK too in workflow dispatch
     */
    public GithubTriggerActionRequest withSetVersion(Optional<String> setVersion) {
        Utils.checkNotNull(setVersion, "setVersion");
        this.setVersion = setVersion;
        return this;
    }

    /**
     * The target name for the action
     */
    public GithubTriggerActionRequest withTargetName(String targetName) {
        Utils.checkNotNull(targetName, "targetName");
        this.targetName = Optional.ofNullable(targetName);
        return this;
    }

    /**
     * The target name for the action
     */
    public GithubTriggerActionRequest withTargetName(Optional<String> targetName) {
        Utils.checkNotNull(targetName, "targetName");
        this.targetName = targetName;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GithubTriggerActionRequest other = (GithubTriggerActionRequest) o;
        return 
            Objects.deepEquals(this.genLockId, other.genLockId) &&
            Objects.deepEquals(this.org, other.org) &&
            Objects.deepEquals(this.repoName, other.repoName) &&
            Objects.deepEquals(this.setVersion, other.setVersion) &&
            Objects.deepEquals(this.targetName, other.targetName);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            genLockId,
            org,
            repoName,
            setVersion,
            targetName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GithubTriggerActionRequest.class,
                "genLockId", genLockId,
                "org", org,
                "repoName", repoName,
                "setVersion", setVersion,
                "targetName", targetName);
    }
    
    public final static class Builder {
 
        private String genLockId;
 
        private String org;
 
        private String repoName;
 
        private Optional<String> setVersion = Optional.empty();
 
        private Optional<String> targetName = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The generation lock ID
         */
        public Builder genLockId(String genLockId) {
            Utils.checkNotNull(genLockId, "genLockId");
            this.genLockId = genLockId;
            return this;
        }

        /**
         * The GitHub organization name
         */
        public Builder org(String org) {
            Utils.checkNotNull(org, "org");
            this.org = org;
            return this;
        }

        /**
         * The GitHub repository name
         */
        public Builder repoName(String repoName) {
            Utils.checkNotNull(repoName, "repoName");
            this.repoName = repoName;
            return this;
        }

        /**
         * A version to override the SDK too in workflow dispatch
         */
        public Builder setVersion(String setVersion) {
            Utils.checkNotNull(setVersion, "setVersion");
            this.setVersion = Optional.ofNullable(setVersion);
            return this;
        }

        /**
         * A version to override the SDK too in workflow dispatch
         */
        public Builder setVersion(Optional<String> setVersion) {
            Utils.checkNotNull(setVersion, "setVersion");
            this.setVersion = setVersion;
            return this;
        }

        /**
         * The target name for the action
         */
        public Builder targetName(String targetName) {
            Utils.checkNotNull(targetName, "targetName");
            this.targetName = Optional.ofNullable(targetName);
            return this;
        }

        /**
         * The target name for the action
         */
        public Builder targetName(Optional<String> targetName) {
            Utils.checkNotNull(targetName, "targetName");
            this.targetName = targetName;
            return this;
        }
        
        public GithubTriggerActionRequest build() {
            return new GithubTriggerActionRequest(
                genLockId,
                org,
                repoName,
                setVersion,
                targetName);
        }
    }
}

