/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.shared;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;

/**
 * GithubConfigureTargetRequest - A request to configure a GitHub target
 */

public class GithubConfigureTargetRequest {

    /**
     * The GitHub organization name
     */
    @JsonProperty("org")
    private String org;

    /**
     * The GitHub repository name
     */
    @JsonProperty("repo_name")
    private String repoName;

    @JsonCreator
    public GithubConfigureTargetRequest(
            @JsonProperty("org") String org,
            @JsonProperty("repo_name") String repoName) {
        Utils.checkNotNull(org, "org");
        Utils.checkNotNull(repoName, "repoName");
        this.org = org;
        this.repoName = repoName;
    }

    /**
     * The GitHub organization name
     */
    @JsonIgnore
    public String org() {
        return org;
    }

    /**
     * The GitHub repository name
     */
    @JsonIgnore
    public String repoName() {
        return repoName;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The GitHub organization name
     */
    public GithubConfigureTargetRequest withOrg(String org) {
        Utils.checkNotNull(org, "org");
        this.org = org;
        return this;
    }

    /**
     * The GitHub repository name
     */
    public GithubConfigureTargetRequest withRepoName(String repoName) {
        Utils.checkNotNull(repoName, "repoName");
        this.repoName = repoName;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GithubConfigureTargetRequest other = (GithubConfigureTargetRequest) o;
        return 
            Objects.deepEquals(this.org, other.org) &&
            Objects.deepEquals(this.repoName, other.repoName);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            org,
            repoName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GithubConfigureTargetRequest.class,
                "org", org,
                "repoName", repoName);
    }
    
    public final static class Builder {
 
        private String org;
 
        private String repoName;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The GitHub organization name
         */
        public Builder org(String org) {
            Utils.checkNotNull(org, "org");
            this.org = org;
            return this;
        }

        /**
         * The GitHub repository name
         */
        public Builder repoName(String repoName) {
            Utils.checkNotNull(repoName, "repoName");
            this.repoName = repoName;
            return this;
        }
        
        public GithubConfigureTargetRequest build() {
            return new GithubConfigureTargetRequest(
                org,
                repoName);
        }
    }
}

