/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
/**
 * GithubMissingPublishingSecretsResponse - A valid response containing MISSING publishing secret keys for a github target
 */

public class GithubMissingPublishingSecretsResponse {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("missing_secrets")
    private Optional<? extends java.util.List<String>> missingSecrets;

    @JsonCreator
    public GithubMissingPublishingSecretsResponse(
            @JsonProperty("missing_secrets") Optional<? extends java.util.List<String>> missingSecrets) {
        Utils.checkNotNull(missingSecrets, "missingSecrets");
        this.missingSecrets = missingSecrets;
    }
    
    public GithubMissingPublishingSecretsResponse() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<java.util.List<String>> missingSecrets() {
        return (Optional<java.util.List<String>>) missingSecrets;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public GithubMissingPublishingSecretsResponse withMissingSecrets(java.util.List<String> missingSecrets) {
        Utils.checkNotNull(missingSecrets, "missingSecrets");
        this.missingSecrets = Optional.ofNullable(missingSecrets);
        return this;
    }

    public GithubMissingPublishingSecretsResponse withMissingSecrets(Optional<? extends java.util.List<String>> missingSecrets) {
        Utils.checkNotNull(missingSecrets, "missingSecrets");
        this.missingSecrets = missingSecrets;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GithubMissingPublishingSecretsResponse other = (GithubMissingPublishingSecretsResponse) o;
        return 
            java.util.Objects.deepEquals(this.missingSecrets, other.missingSecrets);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            missingSecrets);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GithubMissingPublishingSecretsResponse.class,
                "missingSecrets", missingSecrets);
    }
    
    public final static class Builder {
 
        private Optional<? extends java.util.List<String>> missingSecrets = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder missingSecrets(java.util.List<String> missingSecrets) {
            Utils.checkNotNull(missingSecrets, "missingSecrets");
            this.missingSecrets = Optional.ofNullable(missingSecrets);
            return this;
        }

        public Builder missingSecrets(Optional<? extends java.util.List<String>> missingSecrets) {
            Utils.checkNotNull(missingSecrets, "missingSecrets");
            this.missingSecrets = missingSecrets;
            return this;
        }
        
        public GithubMissingPublishingSecretsResponse build() {
            return new GithubMissingPublishingSecretsResponse(
                missingSecrets);
        }
    }
}

