/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.shared;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public class OASOperation {

    @JsonProperty("description")
    private String description;

    @JsonProperty("method")
    private String method;

    @JsonProperty("operation_id")
    private String operationId;

    @JsonProperty("path")
    private String path;

    @JsonProperty("tags")
    private List<String> tags;

    @JsonCreator
    public OASOperation(
            @JsonProperty("description") String description,
            @JsonProperty("method") String method,
            @JsonProperty("operation_id") String operationId,
            @JsonProperty("path") String path,
            @JsonProperty("tags") List<String> tags) {
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(method, "method");
        Utils.checkNotNull(operationId, "operationId");
        Utils.checkNotNull(path, "path");
        Utils.checkNotNull(tags, "tags");
        this.description = description;
        this.method = method;
        this.operationId = operationId;
        this.path = path;
        this.tags = tags;
    }

    @JsonIgnore
    public String description() {
        return description;
    }

    @JsonIgnore
    public String method() {
        return method;
    }

    @JsonIgnore
    public String operationId() {
        return operationId;
    }

    @JsonIgnore
    public String path() {
        return path;
    }

    @JsonIgnore
    public List<String> tags() {
        return tags;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public OASOperation withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    public OASOperation withMethod(String method) {
        Utils.checkNotNull(method, "method");
        this.method = method;
        return this;
    }

    public OASOperation withOperationId(String operationId) {
        Utils.checkNotNull(operationId, "operationId");
        this.operationId = operationId;
        return this;
    }

    public OASOperation withPath(String path) {
        Utils.checkNotNull(path, "path");
        this.path = path;
        return this;
    }

    public OASOperation withTags(List<String> tags) {
        Utils.checkNotNull(tags, "tags");
        this.tags = tags;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OASOperation other = (OASOperation) o;
        return 
            Objects.deepEquals(this.description, other.description) &&
            Objects.deepEquals(this.method, other.method) &&
            Objects.deepEquals(this.operationId, other.operationId) &&
            Objects.deepEquals(this.path, other.path) &&
            Objects.deepEquals(this.tags, other.tags);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            description,
            method,
            operationId,
            path,
            tags);
    }
    
    @Override
    public String toString() {
        return Utils.toString(OASOperation.class,
                "description", description,
                "method", method,
                "operationId", operationId,
                "path", path,
                "tags", tags);
    }
    
    public final static class Builder {
 
        private String description;
 
        private String method;
 
        private String operationId;
 
        private String path;
 
        private List<String> tags;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }

        public Builder method(String method) {
            Utils.checkNotNull(method, "method");
            this.method = method;
            return this;
        }

        public Builder operationId(String operationId) {
            Utils.checkNotNull(operationId, "operationId");
            this.operationId = operationId;
            return this;
        }

        public Builder path(String path) {
            Utils.checkNotNull(path, "path");
            this.path = path;
            return this;
        }

        public Builder tags(List<String> tags) {
            Utils.checkNotNull(tags, "tags");
            this.tags = tags;
            return this;
        }
        
        public OASOperation build() {
            return new OASOperation(
                description,
                method,
                operationId,
                path,
                tags);
        }
    }
}

