/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.shared;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;


public class PreflightRequest {

    @JsonProperty("namespace_name")
    private String namespaceName;

    @JsonCreator
    public PreflightRequest(
            @JsonProperty("namespace_name") String namespaceName) {
        Utils.checkNotNull(namespaceName, "namespaceName");
        this.namespaceName = namespaceName;
    }

    @JsonIgnore
    public String namespaceName() {
        return namespaceName;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public PreflightRequest withNamespaceName(String namespaceName) {
        Utils.checkNotNull(namespaceName, "namespaceName");
        this.namespaceName = namespaceName;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PreflightRequest other = (PreflightRequest) o;
        return 
            Objects.deepEquals(this.namespaceName, other.namespaceName);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            namespaceName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PreflightRequest.class,
                "namespaceName", namespaceName);
    }
    
    public final static class Builder {
 
        private String namespaceName;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder namespaceName(String namespaceName) {
            Utils.checkNotNull(namespaceName, "namespaceName");
            this.namespaceName = namespaceName;
            return this;
        }
        
        public PreflightRequest build() {
            return new PreflightRequest(
                namespaceName);
        }
    }
}

