/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.operations;


public class GetOrganizationUsageRequestBuilder {

    private final SDKMethodInterfaces.MethodCallGetOrganizationUsage sdk;

    public GetOrganizationUsageRequestBuilder(SDKMethodInterfaces.MethodCallGetOrganizationUsage sdk) {
        this.sdk = sdk;
    }

    public GetOrganizationUsageResponse call() throws Exception {

        return sdk.getOrganizationUsageDirect();
    }
}
