/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.operations;

import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;

public class GetOASSummaryRequestBuilder {

    private GetOASSummaryRequest request;
    private final SDKMethodInterfaces.MethodCallGetOASSummary sdk;

    public GetOASSummaryRequestBuilder(SDKMethodInterfaces.MethodCallGetOASSummary sdk) {
        this.sdk = sdk;
    }

    public GetOASSummaryRequestBuilder request(io.github.speakeasy_sdks_staging.javaclientsdk.models.operations.GetOASSummaryRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetOASSummaryResponse call() throws Exception {

        return sdk.getOASSummary(
            request);
    }
}
