/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.operations;

import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;

public class GetRevisionsRequestBuilder {

    private GetRevisionsRequest request;
    private final SDKMethodInterfaces.MethodCallGetRevisions sdk;

    public GetRevisionsRequestBuilder(SDKMethodInterfaces.MethodCallGetRevisions sdk) {
        this.sdk = sdk;
    }

    public GetRevisionsRequestBuilder request(io.github.speakeasy_sdks_staging.javaclientsdk.models.operations.GetRevisionsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetRevisionsResponse call() throws Exception {

        return sdk.getRevisions(
            request);
    }
}
