/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.operations;

import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;

public class GetWorkspaceRequestBuilder {

    private GetWorkspaceRequest request;
    private final SDKMethodInterfaces.MethodCallGetWorkspace sdk;

    public GetWorkspaceRequestBuilder(SDKMethodInterfaces.MethodCallGetWorkspace sdk) {
        this.sdk = sdk;
    }

    public GetWorkspaceRequestBuilder request(io.github.speakeasy_sdks_staging.javaclientsdk.models.operations.GetWorkspaceRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetWorkspaceResponse call() throws Exception {

        return sdk.getWorkspace(
            request);
    }
}
