/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.operations;

import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;

public class PostTagsRequestBuilder {

    private PostTagsRequest request;
    private final SDKMethodInterfaces.MethodCallPostTags sdk;

    public PostTagsRequestBuilder(SDKMethodInterfaces.MethodCallPostTags sdk) {
        this.sdk = sdk;
    }

    public PostTagsRequestBuilder request(io.github.speakeasy_sdks_staging.javaclientsdk.models.operations.PostTagsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public PostTagsResponse call() throws Exception {

        return sdk.postTags(
            request);
    }
}
