/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.operations;

import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;

public class RegisterSchemaRequestBuilder {

    private RegisterSchemaRequest request;
    private final SDKMethodInterfaces.MethodCallRegisterSchema sdk;

    public RegisterSchemaRequestBuilder(SDKMethodInterfaces.MethodCallRegisterSchema sdk) {
        this.sdk = sdk;
    }

    public RegisterSchemaRequestBuilder request(io.github.speakeasy_sdks_staging.javaclientsdk.models.operations.RegisterSchemaRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public RegisterSchemaResponse call() throws Exception {

        return sdk.registerSchema(
            request);
    }
}
