/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.github.speakeasy_sdks_staging.javaclientsdk.models.shared.SuggestOperationIDsOpts;
import io.github.speakeasy_sdks_staging.javaclientsdk.utils.SpeakeasyMetadata;
import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;

/**
 * SuggestOperationIDsRequestBody - The schema file to upload provided as a multipart/form-data file segment.
 */

public class SuggestOperationIDsRequestBody {

    @SpeakeasyMetadata("multipartForm:name=opts,json")
    private Optional<? extends SuggestOperationIDsOpts> opts;

    @SpeakeasyMetadata("multipartForm:file")
    private Schema schema;

    @JsonCreator
    public SuggestOperationIDsRequestBody(
            Optional<? extends SuggestOperationIDsOpts> opts,
            Schema schema) {
        Utils.checkNotNull(opts, "opts");
        Utils.checkNotNull(schema, "schema");
        this.opts = opts;
        this.schema = schema;
    }
    
    public SuggestOperationIDsRequestBody(
            Schema schema) {
        this(Optional.empty(), schema);
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<SuggestOperationIDsOpts> opts() {
        return (Optional<SuggestOperationIDsOpts>) opts;
    }

    @JsonIgnore
    public Schema schema() {
        return schema;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public SuggestOperationIDsRequestBody withOpts(SuggestOperationIDsOpts opts) {
        Utils.checkNotNull(opts, "opts");
        this.opts = Optional.ofNullable(opts);
        return this;
    }

    public SuggestOperationIDsRequestBody withOpts(Optional<? extends SuggestOperationIDsOpts> opts) {
        Utils.checkNotNull(opts, "opts");
        this.opts = opts;
        return this;
    }

    public SuggestOperationIDsRequestBody withSchema(Schema schema) {
        Utils.checkNotNull(schema, "schema");
        this.schema = schema;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SuggestOperationIDsRequestBody other = (SuggestOperationIDsRequestBody) o;
        return 
            Objects.deepEquals(this.opts, other.opts) &&
            Objects.deepEquals(this.schema, other.schema);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            opts,
            schema);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SuggestOperationIDsRequestBody.class,
                "opts", opts,
                "schema", schema);
    }
    
    public final static class Builder {
 
        private Optional<? extends SuggestOperationIDsOpts> opts = Optional.empty();
 
        private Schema schema;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder opts(SuggestOperationIDsOpts opts) {
            Utils.checkNotNull(opts, "opts");
            this.opts = Optional.ofNullable(opts);
            return this;
        }

        public Builder opts(Optional<? extends SuggestOperationIDsOpts> opts) {
            Utils.checkNotNull(opts, "opts");
            this.opts = opts;
            return this;
        }

        public Builder schema(Schema schema) {
            Utils.checkNotNull(schema, "schema");
            this.schema = schema;
            return this;
        }
        
        public SuggestOperationIDsRequestBody build() {
            return new SuggestOperationIDsRequestBody(
                opts,
                schema);
        }
    }
}

