/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.operations;

import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;

public class SuggestOpenAPIRequestBuilder {

    private SuggestOpenAPIRequest request;
    private final SDKMethodInterfaces.MethodCallSuggestOpenAPI sdk;

    public SuggestOpenAPIRequestBuilder(SDKMethodInterfaces.MethodCallSuggestOpenAPI sdk) {
        this.sdk = sdk;
    }

    public SuggestOpenAPIRequestBuilder request(io.github.speakeasy_sdks_staging.javaclientsdk.models.operations.SuggestOpenAPIRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public SuggestOpenAPIResponse call() throws Exception {

        return sdk.suggestOpenAPI(
            request);
    }
}
