/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.speakeasy_sdks_staging.javaclientsdk.models.operations;

import io.github.speakeasy_sdks_staging.javaclientsdk.utils.Utils;

public class UploadReportRequestBuilder {

    private UploadReportRequestBody request;
    private final SDKMethodInterfaces.MethodCallUploadReport sdk;

    public UploadReportRequestBuilder(SDKMethodInterfaces.MethodCallUploadReport sdk) {
        this.sdk = sdk;
    }

    public UploadReportRequestBuilder request(io.github.speakeasy_sdks_staging.javaclientsdk.models.operations.UploadReportRequestBody request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public UploadReportResponse call() throws Exception {

        return sdk.uploadReport(
            request);
    }
}
